// Command sweep-canonical applies the canonical published-library
// shape across every per-CLI entry in this repo. The shape is owned
// upstream by cli-printing-press's skill.md.tmpl and readme.md.tmpl
// (so fresh prints land correctly); this tool retrofits existing
// library/<cat>/<api>/SKILL.md and README.md files to match when an
// upstream template change ships and the existing entries need to
// catch up without a full regeneration.
//
// Originally introduced for the Hermes/OpenClaw frontmatter alignment
// (cli-printing-press
// docs/plans/2026-05-06-002-feat-hermes-openclaw-frontmatter-alignment-plan.md);
// has since broadened to also rewrite the SKILL.md Prerequisites
// section, the README ## Install section, and to insert the README
// Hermes/OpenClaw install blocks. The "frontmatter" name was retired
// because the tool now operates on body content too — its job is
// "apply canonical shape", not "patch frontmatter".
//
// What the tool patches in each library/<cat>/<api>/ directory:
//
// SKILL.md:
//   - Strips legacy OpenClaw env-var declarations (requires.env, envVars,
//     primaryEnv) from frontmatter.
//   - Adds the Hermes-recognized top-level fields (author, license) after
//     the description: line. Strips any pre-existing `version:` line —
//     it was emitted by an earlier sweep but tracked the Press version,
//     conflating generator with skill. Hermes lists `version` as
//     optional; omission is the honest move until per-CLI release
//     versions can be stamped at library CI time from goreleaser tags.
//   - Moves the existing `## CLI Installation` section to immediately
//     after the H1 and rewrites it as `## Prerequisites: Install the
//     CLI` with imperative "you must verify ... do not proceed" wording.
//     For CLIs that lack a `## CLI Installation` section entirely, the
//     Prerequisites section is constructed from manifest data instead.
//
// README.md:
//   - Rewrites the `## Install` section (with its `### Binary` /
//     `### Go` subsections) to lead with the `npx -y
//     @mvanhorn/printing-press-library install <api>` installer (CLI + agent
//     skill), with `--cli-only` and a Go fallback below. Mirrors the
//     upstream readme.md.tmpl change.
//   - Inserts `## Install via Hermes` and `## Install via OpenClaw`
//     sections, anchored on the <!-- pp-hermes-install-anchor -->
//     comment when present, or via a fallback chain (Use with Claude
//     Desktop -> Use with Claude Code -> ## Install -> EOF) for
//     legacy READMEs.
//
// Idempotent: running twice produces zero textual diff on the second run.
// Snapshot-restore: if any per-CLI patch fails, all touched files for
// that CLI are restored from in-memory snapshots before moving on. The
// rest of the sweep continues.
//
// Once every library entry has been swept and the upstream templates
// match, the regen workflow takes over for ongoing changes — fresh
// prints from cli-printing-press already produce canonical-shape
// output, so this tool is only invoked when an upstream template
// change ships and existing entries need to catch up.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type manifest struct {
	CLIName   string `json:"cli_name"`
	APIName   string `json:"api_name"`
	OwnerName string `json:"owner_name"`
}

// cliAuthorByAPIName is the canonical author display name for every
// existing per-CLI library entry, keyed by the api_name (the directory
// basename: dominos, linear, etc.). The entries were derived from
// each CLI's `// Copyright YYYY <slug>.` header where present, with
// per-CLI corrections applied for the cases where the slug doesn't
// reflect actual authorship — generator-fallback "user" headers
// (5 CLIs originally generated by Cathryn before git config was set),
// missing copyright headers (2 legacy CLIs), and one slug-vs-actual
// mismatch (espn — copyright slug "trevin-chow" but actually Matt's
// work).
//
// Entries here are the source of truth for the author: field that
// lands in published library/<cat>/<api>/SKILL.md and the byte-
// identical cli-skills/pp-<api>/SKILL.md mirror. The operator's
// git config is consulted only as a last-resort fallback for new
// CLIs not in this map.
var cliAuthorByAPIName = map[string]string{
	"agent-capture":   "Matt Van Horn",
	"ahrefs":          "Cathryn Lavery",
	"airbnb":          "Matt Van Horn",
	"allrecipes":      "Trevin Chow",
	"amazon-seller":   "Cathryn Lavery",
	"apartments":      "rderwin",
	"archive-is":      "Matt Van Horn",
	"cal-com":         "Trevin Chow",
	"coingecko":       "Hiten Shah",
	"company-goat":    "Trevin Chow",
	"contact-goat":    "Matt Van Horn",
	"craigslist":      "Trevin Chow",
	"docker-hub":      "Hiten Shah",
	"dominos":         "Matt Van Horn",
	"dub":             "Trevin Chow",
	"ebay":            "Matt Van Horn",
	"espn":            "Matt Van Horn",
	"fedex":           "Trevin Chow",
	"firecrawl":       "Hiten Shah",
	"flight-goat":     "Matt Van Horn",
	"food52":          "Trevin Chow",
	"google-photos":   "Cathryn Lavery",
	"hackernews":      "Trevin Chow",
	"instacart":       "Matt Van Horn",
	"kalshi":          "Trevin Chow",
	"klaviyo":         "Cathryn Lavery",
	"linear":          "Matt Van Horn",
	"mercury":         "Cathryn Lavery",
	"movie-goat":      "Trevin Chow",
	"nvd":             "Hiten Shah",
	"open-meteo":      "Trevin Chow",
	"pagliacci":       "Trevin Chow",
	"pokeapi":         "Hiten Shah",
	"postman-explore": "Trevin Chow",
	"producthunt":     "Trevin Chow",
	"pypi":            "Hiten Shah",
	"recipe-goat":     "Trevin Chow",
	"render":          "Giuliano Giacaglia",
	"scrape-creators": "Adrian Horning",
	"seats-aero":      "Cathryn Lavery",
	"sentry":          "Cathryn Lavery",
	"shopify":         "Cathryn Lavery",
	"slack":           "Matt Van Horn",
	"steam-web":       "Trevin Chow",
	"tiktok-shop":     "Cathryn Lavery",
	"trigger-dev":     "Matt Van Horn",
	"weather-goat":    "Trevin Chow",
	"wikipedia":       "Hiten Shah",
	"yahoo-finance":   "Trevin Chow",
}

func main() {
	libraryRoot := "library"
	if v := os.Getenv("SWEEP_LIBRARY_ROOT"); v != "" {
		libraryRoot = v
	}

	// -readme-only / SWEEP_README_ONLY: skip SKILL.md patching entirely.
	// Use this when running the sweep from a workspace whose
	// `git config user.name` differs from the canonical maintainer
	// identity, or when iterating on a README-only template change and
	// you don't want skill churn in the diff. The SKILL.md path is also
	// defended in-place (existing author values are preserved unless
	// they're the placeholder "user"), but this flag is the belt-and-
	// suspenders option when you don't want SKILL.md touched at all.
	readmeOnly := false
	for _, a := range os.Args[1:] {
		if a == "-readme-only" || a == "--readme-only" {
			readmeOnly = true
		}
	}
	if !readmeOnly && strings.EqualFold(os.Getenv("SWEEP_README_ONLY"), "1") {
		readmeOnly = true
	}

	ownerName := strings.TrimSpace(os.Getenv("SWEEP_OWNER_NAME"))
	if ownerName == "" {
		out, err := exec.Command("git", "config", "user.name").Output()
		if err == nil {
			ownerName = strings.TrimSpace(string(out))
		}
	}
	if !readmeOnly && ownerName == "" {
		log.Fatalf("could not resolve owner display name: set SWEEP_OWNER_NAME, or `git config user.name`. " +
			"the value lands as `author:` in the published library/<cat>/<api>/SKILL.md frontmatter " +
			"only when the existing author is missing or is the placeholder \"user\". " +
			"pass -readme-only if you don't want SKILL.md touched at all.")
	}

	cliDirs, err := findCLIDirs(libraryRoot)
	if err != nil {
		log.Fatalf("walking %s: %v", libraryRoot, err)
	}
	if len(cliDirs) == 0 {
		log.Fatalf("no per-CLI directories found under %s", libraryRoot)
	}

	if readmeOnly {
		fmt.Println("Running in -readme-only mode: SKILL.md files will not be touched.")
	}

	var processed, skipped, errored int
	for _, dir := range cliDirs {
		status, err := sweepCLI(dir, ownerName, readmeOnly)
		switch {
		case err != nil:
			fmt.Printf("  ERROR %s: %v\n", dir, err)
			errored++
		case status == statusUnchanged:
			skipped++
		default:
			fmt.Printf("  SWEPT %s (%s)\n", dir, status)
			processed++
		}
	}

	fmt.Printf("\nSweep complete: %d patched, %d already up-to-date, %d errored\n", processed, skipped, errored)
	if errored > 0 {
		os.Exit(1)
	}
}

// findCLIDirs returns library/<cat>/<api>/ directories in deterministic order.
func findCLIDirs(libraryRoot string) ([]string, error) {
	cats, err := os.ReadDir(libraryRoot)
	if err != nil {
		return nil, err
	}
	var dirs []string
	for _, cat := range cats {
		if !cat.IsDir() {
			continue
		}
		catPath := filepath.Join(libraryRoot, cat.Name())
		apis, err := os.ReadDir(catPath)
		if err != nil {
			return nil, err
		}
		for _, api := range apis {
			if !api.IsDir() {
				continue
			}
			dirs = append(dirs, filepath.Join(catPath, api.Name()))
		}
	}
	sort.Strings(dirs)
	return dirs, nil
}

type sweepStatus string

const (
	statusUnchanged  sweepStatus = "unchanged" // both files already at canonical shape
	statusSkillOnly  sweepStatus = "skill-only"
	statusReadmeOnly sweepStatus = "readme-only"
	statusBoth       sweepStatus = "both"
)

const minimumGoVersion = "Go 1.26.3 or newer"

// sweepCLI applies the canonical shape to one library/<cat>/<api>/. The
// snapshot-restore guarantees: on any error from patchSkill or patchReadme,
// every file we wrote so far for this CLI is restored from its snapshot
// before the function returns. Unchanged files are not touched.
//
// readmeOnly skips SKILL.md patching entirely. See main() for when
// callers set this.
func sweepCLI(cliDir, ownerName string, readmeOnly bool) (sweepStatus, error) {
	skillPath := filepath.Join(cliDir, "SKILL.md")
	readmePath := filepath.Join(cliDir, "README.md")
	manifestPath := filepath.Join(cliDir, ".printing-press.json")

	mfData, err := os.ReadFile(manifestPath)
	if err != nil {
		return statusUnchanged, fmt.Errorf("read manifest: %w", err)
	}
	var mf manifest
	if err := json.Unmarshal(mfData, &mf); err != nil {
		return statusUnchanged, fmt.Errorf("parse manifest: %w", err)
	}
	if mf.CLIName == "" {
		return statusUnchanged, fmt.Errorf("manifest missing cli_name")
	}

	// Authority for category: directory path. The manifest's category
	// field is omitempty and missing in 35 of 49 legacy manifests, so
	// trusting the on-disk location is more reliable.
	category := filepath.Base(filepath.Dir(cliDir))
	if category == "" {
		category = "other"
	}

	// Authorship resolution — produces the value used ONLY when the
	// existing SKILL.md author is missing or the placeholder "user"
	// (see ensureFrontmatterTopLevelFields). Real existing authors are
	// preserved unconditionally.
	//
	//  1. cliAuthorByAPIName — the curated per-CLI mapping; the source
	//     of truth for the existing 49 published CLIs. Honors actual
	//     authorship rather than guessing from git history.
	//  2. Manifest's owner_name — set by future fresh prints (R5 in
	//     the upstream plan). Lets a regen preserve attribution.
	//  3. Operator's git config user.name — last-resort fallback for
	//     a new CLI added to the library without an entry in the map
	//     above.
	authorName := cliAuthorByAPIName[mf.APIName]
	if authorName == "" {
		authorName = mf.OwnerName
	}
	if authorName == "" {
		authorName = ownerName
	}

	readmeBefore, err := os.ReadFile(readmePath)
	if err != nil {
		return statusUnchanged, fmt.Errorf("read README.md: %w", err)
	}

	var skillBefore []byte
	var skillAfter string
	var skillChanged bool
	if !readmeOnly {
		skillBefore, err = os.ReadFile(skillPath)
		if err != nil {
			return statusUnchanged, fmt.Errorf("read SKILL.md: %w", err)
		}
		skillAfter, err = patchSkill(string(skillBefore), patchSkillCtx{
			CLIName:    mf.CLIName,
			APIName:    mf.APIName,
			Category:   category,
			AuthorName: authorName,
		})
		if err != nil {
			return statusUnchanged, fmt.Errorf("patch SKILL.md: %w", err)
		}
		skillChanged = skillAfter != string(skillBefore)
	}

	readmeAfter, err := patchReadme(string(readmeBefore), patchReadmeCtx{
		CLIName:  mf.CLIName,
		APIName:  mf.APIName,
		Category: category,
	})
	if err != nil {
		return statusUnchanged, fmt.Errorf("patch README.md: %w", err)
	}

	readmeChanged := readmeAfter != string(readmeBefore)
	if !skillChanged && !readmeChanged {
		return statusUnchanged, nil
	}

	// Snapshot-restore: track which files we've written so we can roll
	// back on later failures within this CLI's patch set.
	var written []struct {
		path   string
		before []byte
	}
	defer func() {
		// no-op on success path; the named return below clears this on success
	}()
	rollback := func() {
		for _, w := range written {
			if rerr := os.WriteFile(w.path, w.before, 0o644); rerr != nil {
				fmt.Printf("    WARN restore %s failed: %v\n", w.path, rerr)
			}
		}
	}

	if skillChanged {
		if err := os.WriteFile(skillPath, []byte(skillAfter), 0o644); err != nil {
			return statusUnchanged, fmt.Errorf("write SKILL.md: %w", err)
		}
		written = append(written, struct {
			path   string
			before []byte
		}{skillPath, skillBefore})
	}
	if readmeChanged {
		if err := os.WriteFile(readmePath, []byte(readmeAfter), 0o644); err != nil {
			rollback()
			return statusUnchanged, fmt.Errorf("write README.md: %w", err)
		}
		written = append(written, struct {
			path   string
			before []byte
		}{readmePath, readmeBefore})
	}

	switch {
	case skillChanged && readmeChanged:
		return statusBoth, nil
	case skillChanged:
		return statusSkillOnly, nil
	default:
		return statusReadmeOnly, nil
	}
}

type patchSkillCtx struct {
	CLIName           string // e.g. "shopify-pp-cli"
	APIName           string // e.g. "shopify"
	Category          string // e.g. "commerce"
	AuthorName        string // display name, e.g. "Trevin Chow"
	FillMissingAuthor bool   // opt in only for dedicated attribution sweeps
}

// patchSkill applies the canonical Hermes/OpenClaw shape to a SKILL.md
// body. Idempotent: if the body already has the canonical Prerequisites
// section near the top and lacks the legacy OpenClaw env declarations,
// it's returned unchanged.
func patchSkill(body string, ctx patchSkillCtx) (string, error) {
	body = patchSkillFrontmatter(body, ctx)
	body = patchSkillPrerequisites(body, ctx)
	body = patchSkillReferences(body, ctx.CLIName)
	return body, nil
}

// patchSkillFrontmatter rewrites the YAML frontmatter region:
//   - Strips `      env: ...` line under requires (4 shapes: empty inline,
//     single inline, block-style, absent).
//   - Strips entire `    envVars:` block including all indented children.
//   - Strips `    primaryEnv: ...` line.
//   - Adds `author`, `license` top-level fields after the `description:`
//     line. Strips any pre-existing `version:` line — see top-of-file
//     comment for why version is omitted.
//
// Body content (after the closing ---) is byte-preserved.
func patchSkillFrontmatter(body string, ctx patchSkillCtx) string {
	const fence = "---\n"
	if !strings.HasPrefix(body, fence) {
		return body
	}
	end := strings.Index(body[len(fence):], "\n"+fence)
	if end < 0 {
		return body
	}
	frontmatter := body[len(fence) : len(fence)+end+1] // include trailing \n
	rest := body[len(fence)+end+len(fence)+1:]         // after second ---\n

	frontmatter = stripFrontmatterLegacyEnvBlocks(frontmatter)
	frontmatter = ensureFrontmatterTopLevelFields(frontmatter, ctx)

	return fence + frontmatter + fence + rest
}

// stripFrontmatterLegacyEnvBlocks removes the legacy OpenClaw env
// declarations from a frontmatter string. Handles all four observed
// shapes:
//   - `      env: []`             (empty inline list)
//   - `      env: ["FOO"]`        (single inline list)
//   - `      env:\n        - FOO` (block-style list with indented items)
//   - `    envVars:\n      - ...` (multi-line envVars block)
//   - `    primaryEnv: VALUE`     (legacy single-key field)
func stripFrontmatterLegacyEnvBlocks(fm string) string {
	lines := strings.Split(fm, "\n")
	var out []string
	skipUntilDedent := -1 // base indent level of a multi-line block being skipped; -1 when not skipping
	for _, line := range lines {
		if skipUntilDedent >= 0 {
			indent := leadingSpaces(line)
			// Skip continuation lines: blank lines or anything more-indented
			// than the block's base. The block ends at the first non-blank
			// line whose indent is <= the base.
			if strings.TrimSpace(line) == "" || indent > skipUntilDedent {
				continue
			}
			skipUntilDedent = -1
			// fall through to evaluate this line normally
		}

		trimmed := strings.TrimLeft(line, " ")
		indent := len(line) - len(trimmed)

		// `      env: ...` under requires (indent 6 in the canonical shape).
		// Catches both inline list ([] or ["FOO"]) and block-style header
		// (just `env:`).
		if indent == 6 && (strings.HasPrefix(trimmed, "env: ") || trimmed == "env:") {
			if trimmed == "env:" {
				// Block-style: skip the indented list items that follow.
				skipUntilDedent = indent
			}
			continue
		}

		// `    envVars:` (indent 4) — strip header AND all indented content
		if indent == 4 && trimmed == "envVars:" {
			skipUntilDedent = indent
			continue
		}

		// `    primaryEnv: VALUE` — single line, no continuation
		if indent == 4 && strings.HasPrefix(trimmed, "primaryEnv:") {
			continue
		}

		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func leadingSpaces(s string) int {
	for i := 0; i < len(s); i++ {
		if s[i] != ' ' {
			return i
		}
	}
	return len(s)
}

// ensureFrontmatterTopLevelFields normalizes `author` and `license` to
// the canonical "after description" position. Both are stripped first
// and re-inserted as a contiguous block, so:
//
//   - Author preserves any existing value already in the frontmatter,
//     including the old generator-fallback placeholder "user". Missing
//     authors are filled only when ctx.FillMissingAuthor is true, so a
//     docs-shape sweep cannot accidentally bundle attribution changes
//     with unrelated README/SKILL surface edits.
//   - License is always "Apache-2.0" — the constant for every printed
//     CLI per LICENSE.tmpl.
//
// Also strips any pre-existing `version:` line (legacy from an earlier
// sweep that emitted the Press version) without re-emitting one. See
// top-of-file comment for the rationale.
//
// Idempotent in the second-run-zero-diff sense — running with the
// same ctx produces the same output.
func ensureFrontmatterTopLevelFields(fm string, ctx patchSkillCtx) string {
	existingAuthor := extractTopLevelFieldValue(fm, "author")
	hasAuthor := topLevelFieldRe("author").FindStringIndex(fm) != nil

	fm = stripTopLevelField(fm, "version")
	fm = stripTopLevelField(fm, "author")
	fm = stripTopLevelField(fm, "license")

	var b strings.Builder
	if hasAuthor {
		fmt.Fprintf(&b, "author: %q\n", existingAuthor)
	} else if ctx.FillMissingAuthor && ctx.AuthorName != "" {
		fmt.Fprintf(&b, "author: %q\n", ctx.AuthorName)
	}
	fmt.Fprintf(&b, "license: %q\n", "Apache-2.0")
	block := b.String()

	descRe := regexp.MustCompile(`(?m)^description: ".*"\n`)
	return descRe.ReplaceAllStringFunc(fm, func(match string) string {
		return match + block
	})
}

// stripTopLevelField removes the line `<name>: "..."\n` from a
// frontmatter string when present at the top level.
func stripTopLevelField(fm, name string) string {
	re := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(name) + `: ".*"\n`)
	return re.ReplaceAllString(fm, "")
}

// extractTopLevelFieldValue returns the quoted value of a top-level
// `<name>: "..."` line in the frontmatter, or "" when absent.
func extractTopLevelFieldValue(fm, name string) string {
	re := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(name) + `: "([^"]*)"$`)
	m := re.FindStringSubmatch(fm)
	if len(m) < 2 {
		return ""
	}
	return m[1]
}

// topLevelFieldRe returns a regexp matching `<name>:` at the start of a
// line — i.e. a top-level (non-indented) frontmatter field.
func topLevelFieldRe(name string) *regexp.Regexp {
	return regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(name) + `:\s`)
}

// patchSkillPrerequisites moves the existing `## CLI Installation`
// section to immediately after the H1 and renames it. For SKILL.md
// files that lack `## CLI Installation` entirely (4 in the live
// library), constructs the section from manifest data. If a
// previous sweep already inserted a `## Prerequisites: Install the
// CLI` section, that prior section is removed and the canonical
// content is re-emitted — so install-command updates (e.g., a
// switch from `go install` to `npx ... install --cli-only`)
// propagate across re-sweeps without manual intervention.
//
// Idempotent in the second-run-zero-diff sense: running with the
// same ctx produces the same Prerequisites content.
func patchSkillPrerequisites(body string, ctx patchSkillCtx) string {
	// Remove an existing Prerequisites section (from a prior sweep) so
	// the canonical content can be re-emitted with any updates.
	body = removePrerequisitesSection(body)

	prereq := buildPrerequisitesSection(ctx)

	// Try to remove the existing `## CLI Installation` section.
	body, removedCLIInstall := removeCLIInstallationSection(body)

	// Insert Prerequisites right after the H1 line. If we couldn't find
	// an H1, insert at the very top after the closing frontmatter ---.
	body = insertAfterH1(body, prereq)

	// If we removed the existing CLI Installation section, also update
	// any remaining references (the Direct Use section's "see CLI
	// Installation above" hint is the canonical one, but other prose
	// may reference it too).
	if removedCLIInstall {
		body = strings.ReplaceAll(body, "(see CLI Installation above)",
			"(see Prerequisites at the top of this skill)")
		// The Argument Parsing rule uses the phrase "CLI installation"
		// in routing guidance — update to point at Prerequisites.
		body = strings.ReplaceAll(body,
			"otherwise → CLI installation",
			"otherwise → see Prerequisites above")
	}

	return body
}

// removePrerequisitesSection strips an existing `## Prerequisites:
// Install the CLI` section (heading + body up to the next `## `
// heading or EOF) so the sweep can re-emit canonical content. Used
// to make install-command updates (e.g., switching the install line
// from `go install` to `npx ... install --cli-only`) propagate
// across re-sweeps.
func removePrerequisitesSection(body string) string {
	const heading = "## Prerequisites: Install the CLI"
	idx := strings.Index(body, heading)
	if idx < 0 {
		return body
	}
	rest := body[idx+len(heading):]
	nextIdx := strings.Index(rest, "\n## ")
	var sectionEnd int
	if nextIdx < 0 {
		sectionEnd = len(body)
	} else {
		sectionEnd = idx + len(heading) + nextIdx + 1
	}
	start := idx
	for start > 0 && body[start-1] == '\n' {
		start--
		if start > 0 && body[start-1] != '\n' {
			break
		}
	}
	return body[:start+1] + body[sectionEnd:]
}

func buildPrerequisitesSection(ctx patchSkillCtx) string {
	module := fmt.Sprintf(
		"github.com/mvanhorn/printing-press-library/library/%s/%s/cmd/%s",
		ctx.Category, ctx.APIName, ctx.CLIName,
	)
	return fmt.Sprintf(`## Prerequisites: Install the CLI

This skill drives the `+"`%s`"+` binary. **You must verify the CLI is installed before invoking any command from this skill.** If it is missing, install it first:

1. Install via the Printing Press installer:
   `+"```bash"+`
   npx -y @mvanhorn/printing-press-library install %s --cli-only
   `+"```"+`
2. Verify: `+"`%s --version`"+`
3. Ensure `+"`$GOPATH/bin`"+` (or `+"`$HOME/go/bin`"+`) is on `+"`$PATH`"+`.

If the `+"`npx`"+` install fails (no Node, offline, etc.), fall back to a direct Go install (requires %s):

`+"```bash"+`
go install %s@latest
`+"```"+`

If `+"`--version`"+` reports "command not found" after install, the install step did not put the binary on `+"`$PATH`"+`. Do not proceed with skill commands until verification succeeds.

`, ctx.CLIName, ctx.APIName, ctx.CLIName, minimumGoVersion, module)
}

// removeCLIInstallationSection strips the existing `## CLI Installation`
// section (heading + body up to the next `## ` heading or EOF). Returns
// the modified body and a bool indicating whether the section was found.
func removeCLIInstallationSection(body string) (string, bool) {
	const heading = "## CLI Installation"
	idx := strings.Index(body, heading)
	if idx < 0 {
		return body, false
	}
	// Find the start of the next `## ` heading after this section.
	rest := body[idx+len(heading):]
	nextIdx := strings.Index(rest, "\n## ")
	var sectionEnd int
	if nextIdx < 0 {
		sectionEnd = len(body)
	} else {
		sectionEnd = idx + len(heading) + nextIdx + 1 // include the \n before next heading
	}
	// Also strip the leading blank line(s) before the heading so removal
	// doesn't leave a double-blank gap.
	start := idx
	for start > 0 && body[start-1] == '\n' {
		start--
		if start > 0 && body[start-1] != '\n' {
			break
		}
	}
	return body[:start+1] + body[sectionEnd:], true
}

// insertAfterH1 inserts content right after the first `# ` heading line.
// If no H1 is found, inserts at the start of the body.
func insertAfterH1(body, content string) string {
	// Find first `# ` line (not `## `).
	lines := strings.Split(body, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, "# ") && !strings.HasPrefix(line, "## ") {
			// Insert two lines after the H1: one blank, then content.
			head := strings.Join(lines[:i+1], "\n")
			tail := strings.Join(lines[i+1:], "\n")
			return head + "\n\n" + content + tail
		}
	}
	return content + body
}

// patchSkillReferences fixes any stale references to the old CLI
// Installation heading in body prose that wasn't caught by the
// removeCLIInstallationSection-conditional rewriter (e.g. when the
// section was already removed by an earlier sweep run but a reference
// lingered).
func patchSkillReferences(body string, cliName string) string {
	body = strings.ReplaceAll(body, "(see CLI Installation above)",
		"(see Prerequisites at the top of this skill)")
	body = strings.ReplaceAll(body,
		"otherwise → CLI installation",
		"otherwise → see Prerequisites above")
	return body
}

type patchReadmeCtx struct {
	CLIName  string
	APIName  string
	Category string
}

// patchReadme applies the canonical README shape:
//  1. Rewrites the `## Install` section to lead with the `npx -y
//     @mvanhorn/printing-press-library install <api>` installer (CLI + agent
//     skill), with `--cli-only` and a Go fallback below. Mirrors the
//     upstream readme.md.tmpl shape.
//  2. Inserts the `## Install via Hermes` and `## Install via
//     OpenClaw` sections.
//
// Both steps are idempotent in the second-run-zero-diff sense.
func patchReadme(body string, ctx patchReadmeCtx) (string, error) {
	body = patchReadmeInstall(body, ctx)
	body = patchReadmeHermesOpenClaw(body, ctx)
	return body, nil
}

// patchReadmeInstall finds the `## Install` heading and rewrites its
// body up to the next `## ` heading with the canonical block (npx
// default → `--cli-only` → Go fallback → pre-built binary).
//
// Idempotent: running with the same ctx produces the same output. We
// achieve this by always re-emitting the canonical block — running
// against a body that already has the canonical content produces the
// same canonical content.
//
// READMEs without a `## Install` section (2 in the live library:
// agent-capture and the contact-goat manuscript copy) are left
// untouched. Adding an Install section to those is out of scope —
// they have hand-shaped install guidance that doesn't fit the
// template.
func patchReadmeInstall(body string, ctx patchReadmeCtx) string {
	// Match the literal H2 with trailing newline so we don't pick up
	// `## Install via Hermes`, `## Installation`, etc.
	const heading = "## Install\n"
	idx := strings.Index(body, heading)
	if idx < 0 {
		return body
	}

	// Find the next H2 heading after this one — that's where the
	// Install section ends. Match `\n## ` to avoid matching `### `.
	tail := body[idx+len(heading):]
	nextIdx := strings.Index(tail, "\n## ")
	var sectionEnd int
	if nextIdx < 0 {
		sectionEnd = len(body)
	} else {
		sectionEnd = idx + len(heading) + nextIdx + 1 // include the \n before next heading
	}

	canonical := buildReadmeInstallSection(ctx)
	return body[:idx] + canonical + body[sectionEnd:]
}

func buildReadmeInstallSection(ctx patchReadmeCtx) string {
	module := fmt.Sprintf(
		"github.com/mvanhorn/printing-press-library/library/%s/%s/cmd/%s",
		ctx.Category, ctx.APIName, ctx.CLIName,
	)
	return fmt.Sprintf(`## Install

The recommended path installs both the `+"`%s`"+` binary and the `+"`pp-%s`"+` agent skill (Claude Code, Codex, Cursor, Gemini CLI, GitHub Copilot, and other agents supported by the upstream [`+"`skills`"+`](https://github.com/vercel-labs/skills) CLI) in one shot:

`+"```bash"+`
npx -y @mvanhorn/printing-press-library install %s
`+"```"+`

For CLI only (no skill):

`+"```bash"+`
npx -y @mvanhorn/printing-press-library install %s --cli-only
`+"```"+`

For skill only — installs the skill into the same agents as the default command above, but skips the CLI binary (use this to update or reinstall just the skill):

`+"```bash"+`
npx -y @mvanhorn/printing-press-library install %s --skill-only
`+"```"+`

To constrain the skill install to one or more specific agents (repeatable — agent names match the [`+"`skills`"+`](https://github.com/vercel-labs/skills) CLI):

`+"```bash"+`
npx -y @mvanhorn/printing-press-library install %s --agent claude-code
npx -y @mvanhorn/printing-press-library install %s --agent claude-code --agent codex
`+"```"+`

### Without Node (Go fallback)

If `+"`npx`"+` isn't available (no Node, offline), install the CLI directly via Go (requires %s):

`+"```bash"+`
go install %s@latest
`+"```"+`

This installs the CLI only — no skill.

### Pre-built binary

Download a pre-built binary for your platform from the [latest release](https://github.com/mvanhorn/printing-press-library/releases/tag/%s-current). On macOS, clear the Gatekeeper quarantine: `+"`xattr -d com.apple.quarantine <binary>`"+`. On Unix, mark it executable: `+"`chmod +x <binary>`"+`.

`,
		ctx.CLIName, // binary name in headline
		ctx.APIName, // skill name in headline
		ctx.APIName, // bundled install slug
		ctx.APIName, // --cli-only slug
		ctx.APIName, // --skill-only slug
		ctx.APIName, // --agent single slug
		ctx.APIName, // --agent multi slug
		minimumGoVersion,
		module,      // Go fallback module
		ctx.APIName, // pre-built release tag
	)
}

// patchReadmeHermesOpenClaw enforces the canonical position and
// naming for the alternate install paths grouped at the top of the
// README:
//
//  1. Strips any existing Hermes/OpenClaw sections and the
//     pp-hermes-install-anchor comment from wherever they currently
//     are. Handles both legacy "Install via X" naming and current
//     "Install for X" naming, so the function is forward- and
//     backward-compatible across template versions.
//  2. Strips the legacy `## Use with Claude Code` section entirely —
//     its skill-install command is now redundant with the
//     `--skill-only` and `--agent` options documented in the canonical
//     `## Install` block, and its MCP `<details>` subsection drifted
//     in placement across CLIs without adding value.
//  3. Extracts the `## Use with Claude Desktop` section (when present —
//     not every CLI ships an MCPB bundle) so it can be re-inserted at
//     the canonical position alongside Hermes/OpenClaw. Claude Desktop
//     is a separate install path because the MCPB bundle is its own
//     thing — parallel to Hermes and OpenClaw, not duplicative of
//     `## Install`.
//  4. Re-inserts the canonical install paths (preceded by the anchor
//     comment) immediately after the `## Install` section ends:
//     Hermes → OpenClaw → Claude Desktop (when present). All install
//     paths now sit grouped at the top of the README.
//
// Idempotent: running with body that already has the canonical shape
// strips and re-inserts identical content, producing zero diff. The
// Claude Desktop section is moved verbatim — the sweep does not
// reformat its content, only its position.
//
// READMEs without a `## Install` heading (only agent-capture in the
// live library) are left unchanged — their hand-shaped install
// guidance doesn't fit the template, and dropping the alternate-install
// blocks at an arbitrary position would be worse than leaving them
// off entirely.
func patchReadmeHermesOpenClaw(body string, ctx patchReadmeCtx) string {
	// If there's no ## Install heading to anchor on, don't touch the
	// README — stripping existing alternate-install blocks without
	// being able to re-insert them would silently delete install
	// instructions. Only agent-capture among the live CLIs falls in
	// this branch; its README has hand-shaped install guidance that
	// doesn't fit the template.
	const installHeading = "## Install\n"
	if !strings.Contains(body, installHeading) {
		return body
	}

	// Extract the Claude Desktop section verbatim (heading + body up to
	// the next H2) so we can re-insert it at the canonical position. If
	// the CLI doesn't ship an MCPB bundle, there's no section to move
	// and this stays empty — the canonical block omits the Claude
	// Desktop line entirely.
	claudeDesktopSection := extractH2Section(body, "## Use with Claude Desktop")
	// Strip any anchor comment that fell inside the extracted section
	// (e.g., trigger-dev's pre-PR layout had the anchor sitting between
	// the Claude Desktop body and the next H2). Without this, the
	// stale anchor rides along to the canonical position and produces
	// a duplicate alongside the canonical anchor we re-insert below.
	// Both are stripped from the rest of `body` later, but the
	// extracted section needs its own pass.
	claudeDesktopSection = strings.ReplaceAll(claudeDesktopSection, "<!-- pp-hermes-install-anchor -->\n", "")
	claudeDesktopSection = strings.ReplaceAll(claudeDesktopSection, "<!-- pp-hermes-install-anchor -->", "")

	// Strip the redundant ## Use with Claude Code section entirely.
	// Its content is now covered by the canonical `## Install` block
	// (which documents `--skill-only` and `--agent` flags), and the MCP
	// `<details>` subsection that lived inside it was unstructured and
	// inconsistent across CLIs.
	body = stripH2Section(body, "## Use with Claude Code")

	// Strip stale alternate-install sections from wherever they are.
	// List both Hermes/OpenClaw naming variants so we can migrate "via"
	// to "for" without a separate code path; strip Claude Desktop so
	// the re-insert below can place it at the canonical position.
	for _, h := range []string{
		"## Install via Hermes",
		"## Install via OpenClaw",
		"## Install for Hermes",
		"## Install for OpenClaw",
		"## Use with Claude Desktop",
	} {
		body = stripH2Section(body, h)
	}
	// Strip the anchor comment with or without trailing newline.
	body = strings.ReplaceAll(body, "<!-- pp-hermes-install-anchor -->\n", "")
	body = strings.ReplaceAll(body, "<!-- pp-hermes-install-anchor -->", "")
	// Collapse any blank-line gaps left by stripping (e.g. two adjacent
	// stripped sections leave `\n\n\n` between surrounding content).
	for strings.Contains(body, "\n\n\n") {
		body = strings.ReplaceAll(body, "\n\n\n", "\n\n")
	}

	// Build the canonical block: anchor + Hermes + OpenClaw + Claude
	// Desktop (when the CLI has one). The Claude Desktop section is
	// passed through verbatim.
	canonical := "<!-- pp-hermes-install-anchor -->\n" + buildReadmeInstallSections(ctx)
	if claudeDesktopSection != "" {
		// Ensure exactly one blank line separates the OpenClaw block
		// (which ends with "\n\n") from the moved Claude Desktop
		// section. extractH2Section preserves the section's own
		// trailing blank line; no extra separator needed.
		canonical += claudeDesktopSection
	}

	installIdx := strings.Index(body, installHeading)
	if installIdx < 0 {
		// Defensive: shouldn't reach here given the early-return above,
		// but keep the guard in case body got transformed unexpectedly.
		return body
	}
	// Find the next H2 after ## Install. That's the section boundary
	// where we insert (right before whatever comes next, typically
	// ## Authentication or ## Quick Start).
	tail := body[installIdx+len(installHeading):]
	nextH2Idx := strings.Index(tail, "\n## ")
	if nextH2Idx < 0 {
		// ## Install is the last section in the README. Append at
		// EOF, ensuring a trailing newline boundary.
		if !strings.HasSuffix(body, "\n") {
			body += "\n"
		}
		return body + "\n" + canonical
	}
	insertPos := installIdx + len(installHeading) + nextH2Idx + 1
	return body[:insertPos] + canonical + body[insertPos:]
}

// extractH2Section returns the full `## <heading>` section verbatim
// (heading line + body up to the next `## ` heading or EOF). Returns
// "" if the heading is not present. The returned content includes the
// section's trailing blank line so it can be concatenated directly
// without needing a separator.
func extractH2Section(body, heading string) string {
	needle := heading + "\n"
	idx := strings.Index(body, needle)
	if idx < 0 {
		return ""
	}
	rest := body[idx+len(needle):]
	nextIdx := strings.Index(rest, "\n## ")
	if nextIdx < 0 {
		// Section runs to EOF.
		return body[idx:]
	}
	return body[idx : idx+len(needle)+nextIdx+1]
}

// stripH2Section removes a `## <heading>` section (heading line + body
// up to the next `## ` heading or EOF) from body. Returns body
// unchanged if the heading is not present. Preserves the blank line
// from the previous section's trailing content; surrounding content
// is otherwise byte-preserved.
func stripH2Section(body, heading string) string {
	needle := heading + "\n"
	idx := strings.Index(body, needle)
	if idx < 0 {
		return body
	}
	rest := body[idx+len(needle):]
	nextIdx := strings.Index(rest, "\n## ")
	var sectionEnd int
	if nextIdx < 0 {
		sectionEnd = len(body)
	} else {
		sectionEnd = idx + len(needle) + nextIdx + 1
	}
	return body[:idx] + body[sectionEnd:]
}

func buildReadmeInstallSections(ctx patchReadmeCtx) string {
	return fmt.Sprintf("## Install for Hermes\n\n"+
		"From the Hermes CLI:\n\n"+
		"```bash\n"+
		"hermes skills install mvanhorn/printing-press-library/cli-skills/pp-%s --force\n"+
		"```\n\n"+
		"Inside a Hermes chat session:\n\n"+
		"```bash\n"+
		"/skills install mvanhorn/printing-press-library/cli-skills/pp-%s --force\n"+
		"```\n\n"+
		"## Install for OpenClaw\n\n"+
		"Tell your OpenClaw agent (copy this):\n\n"+
		"```\n"+
		"Install the pp-%s skill from https://github.com/mvanhorn/printing-press-library/tree/main/cli-skills/pp-%s. The skill defines how its required CLI can be installed.\n"+
		"```\n\n",
		ctx.APIName, ctx.APIName, ctx.APIName, ctx.APIName,
	)
}
